web/django/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

web/django/z/board/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('', views.board, name='board'),
    
    path('', views.board_list, name='board'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('post/create/', views.create, name='create'),
    path('post/modify/<int:post_id>/', views.modify, name='modify'),
    path('post/delete/<int:post_id>/', views.delete, name='delete'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('post/vote/<int:post_id>/', views.vote, name='vote'),
]

web/django/z/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("eat/", include("eat.urls")),
    path("drink/", include("drink.urls")),
    path("play/", include("play.urls")),
    path("pay/", include("pay.urls")),
    path("board/", include("board.urls")),
    path("users/", include("users.urls")),
]

web/django/z2/board/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # path('', views.board, name='board'),
    
    path('', views.board_list, name='board'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('post/create/', views.create, name='create'),
    path('post/modify/<int:post_id>/', views.modify, name='modify'),
    path('post/delete/<int:post_id>/', views.delete, name='delete'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('post/vote/<int:post_id>/', views.vote, name='vote'),
]

web/django/0202where4/board/models.py
from django.db import models
from users.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('board:index', args=[self.name])

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')
    view_cnt = models.BigIntegerField(default=0) # 조회수
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_post')
    notice = models.BooleanField(default=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/0203where/board/models.py
from django.db import models
from users.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('board:index', args=[self.name])

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')
    view_cnt = models.BigIntegerField(default=0) # 조회수
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_post')
    notice = models.BooleanField(default=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/0203where_final/board/models.py
from django.db import models
from users.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('board:index', args=[self.name])

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')
    view_cnt = models.BigIntegerField(default=0) # 조회수
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_post')
    notice = models.BooleanField(default=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/0204where2/board/models.py
from django.db import models
from users.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('board:index', args=[self.name])

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')
    view_cnt = models.BigIntegerField(default=0) # 조회수
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_post')
    notice = models.BooleanField(default=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/app4/comment/models.py
from django.db import models
from post.models import Post
from django.contrib.auth.models import User 
from notifications.models import Notification

from django.db.models.signals import post_save, post_delete

# Create your models here.

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def user_comment_post(sender, instance, *args, **kwargs):
		comment = instance
		post = comment.post
		text_preview = comment.body[:90]
		sender = comment.user
		notify = Notification(post=post, sender=sender, user=post.user, text_preview=text_preview ,notification_type=2)
		notify.save()

	def user_del_comment_post(sender, instance, *args, **kwargs):
		like = instance
		post = like.post
		sender = like.user

		notify = Notification.objects.filter(post=post, sender=sender, notification_type=2)
		notify.delete()

#Comment
post_save.connect(Comment.user_comment_post, sender=Comment)
post_delete.connect(Comment.user_del_comment_post, sender=Comment)

web/django/board/board/board/board/models.py
from django.db import models
from django.contrib.auth.models import User

# 질문 모델
# 제목(Char-200), 내용(TextField), 작성날짜, 수정날짜 - DateTimeField
class Question(models.Model):
    subject = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자",related_name="author_question")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    voter = models.ManyToManyField(User, related_name="voter_question",verbose_name="추천수")
    view_cnt = models.BigIntegerField(default=0) # 조회수


class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip



# 답변 모델
# 질문(어떤 질문에 대한 답변인지 파악), 답변내용, 작성날짜, 수정날짜
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자",related_name="author_answer")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    voter = models.ManyToManyField(User, related_name="voter_answer",verbose_name="추천수")



# 댓글 모델(작성자, 작성날짜, 수정날짜, 댓글내용, 질문에 대한 댓글, 답변에 대한 댓글)
# 질문, 답변 모두 댓글 기능 사용
# 모델 정의 1. 따로 처리(질문_댓글, 답변_댓글)
#           2. 같이 사용(필드로 구별)
class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True,blank=True) # 답변에 대한 댓글일 경우 이 부분은 입력 안됨
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE,null=True,blank=True) # 질문에 대한 댓글일 경우 이 부분은 입력 안됨

web/django/board/board/board/models.py
from django.db import models
from django.contrib.auth.models import User

# 질문 모델
# 제목(Char-200), 내용(TextField), 작성날짜, 수정날짜 - DateTimeField
class Question(models.Model):
    subject = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자",related_name="author_question")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    voter = models.ManyToManyField(User, related_name="voter_question",verbose_name="추천수")
    view_cnt = models.BigIntegerField(default=0) # 조회수


class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip



# 답변 모델
# 질문(어떤 질문에 대한 답변인지 파악), 답변내용, 작성날짜, 수정날짜
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자",related_name="author_answer")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    voter = models.ManyToManyField(User, related_name="voter_answer",verbose_name="추천수")



# 댓글 모델(작성자, 작성날짜, 수정날짜, 댓글내용, 질문에 대한 댓글, 답변에 대한 댓글)
# 질문, 답변 모두 댓글 기능 사용
# 모델 정의 1. 따로 처리(질문_댓글, 답변_댓글)
#           2. 같이 사용(필드로 구별)
class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="작성자")
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성날짜")
    modified_at = models.DateTimeField(auto_now=True, verbose_name="수정날짜")
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True,blank=True) # 답변에 대한 댓글일 경우 이 부분은 입력 안됨
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE,null=True,blank=True) # 질문에 대한 댓글일 경우 이 부분은 입력 안됨

web/django/board/board/board/user/models.py
from django.db import models

# Create your models here.

web/django/board/board/user/models.py
from django.db import models

# Create your models here.

web/django/board/user/models.py
from django.db import models

# Create your models here.

web/django/community/board/models.py
from django.db import models
from users.models import User
from taggit.managers import TaggableManager

# title, content, writer(User), registed_dttm
class Board(models.Model):
    title = models.CharField(verbose_name='제목', max_length=120)
    contents = models.TextField(verbose_name='내용') # 테이블이 만들어지기는 content 로 만들어졌어요=>이름 변경하고 다시 마이그레이션 하면
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성자')
    registered_dttm = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    
    tags = TaggableManager()

web/django/z/board/models.py
from django.db import models
from users.models import User

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/0202where4/board/forms.py
from django import forms
from board.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

web/django/0203where/board/forms.py
from django import forms
from board.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

web/django/0203where_final/board/forms.py
from django import forms
from board.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

web/django/0204where2/board/forms.py
from django import forms
from board.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

web/django/app4/comment/forms.py
from django import forms
from comment.models import Comment

class CommentForm(forms.ModelForm):
	body = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}), required=True)

	class Meta:
		model = Comment
		fields = ('body',)

web/django/board/board/board/board/forms.py
from .models import Question,Answer,Comment
from django import forms

# QuestionForm 작성 - subject, content
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject','content']

# AnswerForm - content
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

web/django/board/templates/board/answer_form.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">
      답변 수정
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="content">답변 내용</label>
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">답변 수정</button>
    </form>
  </div>
{% endblock contents %}

web/django/board/templates/board/comment_form.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">
      댓글 등록
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="content">댓글 내용</label>
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">댓글 등록</button>
    </form>
  </div>
{% endblock contents %}

web/django/board/templates/board/question_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block style %}
  <style>
    .comment {
      border-top: dotted 1px #ddd;
      font-size: 0.8em;
    }
  </style>
{% endblock style %}
{% block contents %}
  <div class="container my-3">
    {% if messages %}
      <div class="alert alert-danger my-3">
        {% for msg in messages %}
          <strong>{{msg.tags}}</strong>
          <ul>
            <li>{{msg.message}}</li>
          </ul>
        {% endfor %}
      </div>
    {% endif %}
    <h2 class="border-bottom py-2">
      <!--질문 제목-->
      {{question.subject}}
    </h2>
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
        <a href="#" data-uri="{% url 'vote_question' question.id %}" class="recommend btn btn-sm btn-secondary d-grid my-1">추천</a>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
              <!--질문내용-->
              {{question.content|mark}}
            </div>
            <div class="d-flex justify-content-end">
              <div class="badge bg-secondary p-2">
                <!--작성자-->
                <div class="mb-2 text-start">{{question.author.username}}</div>
                <!--질문작성날짜-->
                {{question.created_at}}
              </div>
            </div>
            {% if question.modified_at %}
              <div class="d-flex justify-content-end pt-1">
                <div class="badge bg-secondary p-2">
                  <div class="mb-2 text-start">modified_at</div>
                  <!--수정날짜-->
                  {{question.modified_at}}
                </div>
              </div>
            {% endif %}
            <!-- 로그인 사용자와 글쓴이가 같다면-->
            {% if question.author == request.user %}
              <div class="my-3">
                <a href="{% url 'question_update' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="btn btn-sm btn-outline-danger" data-uri="{% url 'question_delete' question.id %}">삭제</a>
              </div>
            {% endif %}
            <!--질문 댓글 영역-->
            {% if question.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in question.comment_set.all %}
                  <!--앵커 부분-->
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{comment.content}}</span>
                    <span>-
                      {{comment.author}},
                      {{comment.created_at}}
                      (수정 :
                      {{comment.modified_at}}
                      )</span>
                    <!--댓글작성자와 로그인 사용자가 같다면-->
                    {% if request.user == comment.author %}
                      <a href="{% url 'comment_question_update' comment.id %}" class="small">수정</a>
                      <a href="#" data-uri="{% url 'comment_question_delete' comment.id %}" class="small delete">삭제</a>
                    {% endif %}
                  </div>
                {% endfor %}
              </div>
            {% endif %}
            <div>
              <a href="{% url 'comment_question_create' question.id %}" class="small">댓글 추가....</a>
            </div>
            <!--질문 댓글 영역 종료-->
          </div>
          <!--질문 card body 종료-->
        </div>

        <form action="{% url 'index' %}" id="listForm">
          <input type="hidden" name="keyword" value="{{keyword|default_if_none:''}}" class="keyword">
          <input type="hidden" name="page" value="{{page|default_if_none:''}}" id="page">
          <input type="hidden" name="so" value="{{so|default_if_none:''}}" id="sort">
        </form>
        <a href="" class="back_to_list btn btn-primary btn-sm my-4">
          <i class="bi bi-list">목록으로</i>
        </a>

      </div>
    </div>

    <!--답변 영역 시작-->
    <h5 class="border-bottom my-3 py-2">
      <!--답변 개수-->
      {{question.answer_set.count}}
      개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
      <a name="answer_{{answer.id}}"></a>
      <div class="row my-3">
        <div class="col-1">
          <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
          <a href="#" data-uri="{% url 'vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary d-grid my-1">추천</a>
        </div>
        <div class="col-11">
          <div class="card">
            <div class="card-body">
              <div class="card-text" style="white-space: pre-line">
                <!--답변내용-->
                {{answer.content|mark}}
              </div>
              <div class="d-flex justify-content-end">
                <div class="badge bg-secondary p-2">
                  <!--작성자-->
                  <div class="mb-2 text-start">{{answer.author.username}}</div>
                  <!--답변 작성날짜-->
                  {{answer.created_at}}
                </div>
              </div>
              {% if answer.modified_at %}
                <div class="d-flex justify-content-end pt-1">
                  <div class="badge bg-secondary p-2">
                    <div class="mb-2 text-start">modified_at</div>
                    <!--수정날짜-->
                    {{answer.modified_at}}
                  </div>
                </div>
              {% endif %}
              {% if answer.author == request.user %}
                <div class="my-3">
                  <a href="{% url 'answer_update' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="#" data-uri="{% url 'answer_delete' answer.id %}" class="btn btn-sm btn-outline-danger">삭제</a>
                </div>
              {% endif %}
              <!--답변 댓글 영역-->
              {% if answer.comment_set.count > 0 %}
                <div class="mt-3">
                  {% for comment in answer.comment_set.all %}
                    <!--앵커 부분-->
                    <a name="comment_{{comment.id}}"></a>
                    <div class="comment py-2 text-muted">
                      <span style="white-space: pre-line;">{{comment.content}}</span>
                      <span>-
                        {{comment.author}},
                        {{comment.created_at}}
                        (수정 :
                        {{comment.modified_at}}
                        )</span>
                      <!--댓글작성자와 로그인 사용자가 같다면-->
                      {% if request.user == comment.author %}
                        <a href="{% url 'comment_answer_update' comment.id %}" class="small">수정</a>
                        <a href="#" data-uri="{% url 'comment_answer_delete' comment.id %}" class="small delete">삭제</a>
                      {% endif %}
                    </div>
                  {% endfor %}
                </div>
              {% endif %}
              <div>
                <a href="{% url 'comment_answer_create' answer.id %}" class="small">댓글 추가....</a>
              </div>
              <!--답변 댓글 영역 종료-->
            </div>
          </div>
        </div>
      </div>
    {% endfor %}

    <!--답변 작성 폼 -->
    {% include 'form_errors.html' %}
    <form action="{% url 'answer_create' question.id %}" method="post">
      {% csrf_token %}
      <div class="form-group mb-3">
        <textarea name="content" id="content" rows="10" class="form-control" {% if not user.is_authenticated %} disabled="disabled" {% endif %}></textarea>
      </div>
      <button type="submit" class="btn btn-primary">답변 등록</button>
    </form>
    <!--답변 내용 종료-->
  </div>
{% endblock contents %}
{% block script %}
  <script>
    //질문(답변) 삭제 버튼 클릭 시 confirm('정말로 삭제하시겠습니까?')
    /*
    let elements = document.querySelectorAll('.btn-outline-danger');

    elements.forEach((ele, idx) => {
      ele.addEventListener("click", (e) => {
        // confirm() : 확인을 클릭하면, data-uri 값을 가지고 오기, location.href = 가져온 data-uri 대입
        if (confirm('정말로 삭제하시겠습니까?')) {
          //console.log("경로 ", e.target.dataset.uri);
          location.href = e.target.dataset.uri;
        }
      })
    })


    //목록으로 클릭 시 listForm submit 시키기
    document
      .querySelector(".back_to_list")
      .addEventListener('click', (e) => {
        e.preventDefault();
        document
          .querySelector("#listForm")
          .submit();
      })
    */

    $(function () {
      $('.btn-outline-danger, .delete').on("click", function (e) {
        if (confirm('정말로 삭제하시겠습니까?')) {
          location.href = $(this).data('uri');
        }
      })

      // 추천 버튼 클릭 시 정말로 추천하시겠습니까?
      $(".recommend").on("click", function (e) {
        if (confirm('정말로 추천하시겠습니까?')) {
          location.href = $(this).data('uri');
        }
      })

      //목록으로 클릭 시 listForm submit 시키기
      $(".back_to_list").on('click', (e) => {
        e.preventDefault();
        $("#listForm").submit();
      })

    })
  </script>
{% endblock script %}

web/django/board/templates/board/question_form.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">
      질문등록
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="subject">제목</label>
        <input type="text" name="subject" id="subject" class="form-control">
      </div>
      <div class="form-group mb-3">
        <label for="content">내용</label>
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">질문등록</button>
    </form>
  </div>
{% endblock contents %}

web/django/board/templates/board/question_update.html
{% extends 'base.html' %}
{% block contents %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">
      질문수정
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="subject">제목</label>
        <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value}}">
      </div>
      <div class="form-group mb-3">
        <label for="content">내용</label>
        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value}}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">질문수정</button>
    </form>
  </div>
{% endblock contents %}