web/django/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

web/django/z/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("eat/", include("eat.urls")),
    path("drink/", include("drink.urls")),
    path("play/", include("play.urls")),
    path("pay/", include("pay.urls")),
    path("board/", include("board.urls")),
    path("users/", include("users.urls")),
]

web/django/z/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

web/django/z2/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

web/django/z3/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    path('post/list/', views.index, name='index'),
    path('post/list/<str:category_name>/', views.index, name='index'),
    path('post/detail/<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('post/create/<str:category_name>/', views.create, name='create'),
    path('post/modify/<int:post_id>/', views.modify, name='modify'),
    path('post/delete/<int:post_id>/', views.delete, name='delete'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('post/vote/<int:post_id>/', views.vote, name='vote'),
]

web/django/0202where4/users/models.py
from django.db import models
import os
import uuid
from django.db.models import UniqueConstraint
from django.dispatch import receiver
from django.db.models.signals import post_save

from django.contrib.auth.models import (
    AbstractBaseUser,
    AbstractUser,
    BaseUserManager,
    PermissionsMixin,
    UserManager,
)

# AbstractUser
# AbstractBaseUser 상속
# username, first_name, last_name, email
# is_staff, is_active,  date_joined


# AbstractBaseUser
# password, last_login, is_active


# User 객체
# 속성 - username, password, email(필수요소가 아님), first_name, last_name


# 프로젝트에서 필요한 User
# email 필드 == id 개념 == username
# gender 필드(필수는 아님)
# password
# name 필수


class UserManger(BaseUserManager):
    def _create_user(self, email, password, name, phone, **extra_fields):
        """
        Create and save a user with the given email,password,name.
        """
        if not email:
            raise ValueError("The given email must be set")

        email = self.normalize_email(email)

        user = self.model(email=email, name=name, phone=phone, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, name, phone, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, name, phone, **extra_fields)

    def create_superuser(self, email, password, name, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, name, phone=None, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User 생성 : AbstractUser 상속 or AbstractBaseUser 상속
    필드 추가 : email, password, name, phone

    권한 여부 추가
    """

    # null=True 지정하지 않으면 not null, + unique ==> pk 속성
    email = models.EmailField(verbose_name="이메일", max_length=255, unique=True)
    password = models.CharField(verbose_name="비밀번호", max_length=128)
    name = models.CharField(verbose_name="이름", max_length=64)
    # phone : 비어 있거나 null 허용(선택적 입력)
    phone = models.CharField(verbose_name="핸드폰", max_length=50, blank=True, null=True)

    is_staff = models.BooleanField(verbose_name="관리자여부", default=False)
    is_active = models.BooleanField(verbose_name="활성화여부", default=True)

    # CustomUser 를 기반으로 user 생성을 도와줄 매니저 클래스 등록
    objects = UserManger()  # User.objects.create_user() 생성

    # username(아이디)으로 사용할 필드 지정
    USERNAME_FIELD = "email"

    # email, password 요소 외에 사용자 생성 시 꼭 받아야 하는 필드 작성
    REQUIRED_FIELDS = ["name"]

    def __str__(self) -> str:
        return "<%d %s %s>" % (self.pk, self.email, self.name)

class Profile(models.Model):
    """
    회원가입 시 무조건 같이 실행
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="회원")
    image = models.ImageField(upload_to="profile", default="profile/default.png", verbose_name="프로필 이미지")
    
    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
           Profile.objects.create(user=instance)


class BaseModel(models.Model):
    """
    추상클래스 (껍데기-틀)
    """
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정날짜')
    
    class Meta:
        abstract = True

class Content(BaseModel):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='작성자')
    text = models.TextField(default='')
    
    class Meta:
        ordering = ['-created_at']


def image_upload_to(instance, filename):
    """
    flower.jpg => filename.split('.')[-1] => flower ,jpg
    uuid.uuid4() => 16진수 랜덤값 생성
    00000000-0000-0000-0000-000000000000.jpg
    """
    
    ext = filename.split('.')[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))

class Image(BaseModel):
    UPLOAD_PATH = 'user-upload'
    
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name='작성글')
    image = models.ImageField(upload_to=image_upload_to)
    order = models.SmallIntegerField()

web/django/0203where/users/models.py
from django.db import models
import os
import uuid
from django.db.models import UniqueConstraint
from django.dispatch import receiver
from django.db.models.signals import post_save

from django.contrib.auth.models import (
    AbstractBaseUser,
    AbstractUser,
    BaseUserManager,
    PermissionsMixin,
    UserManager,
)

# AbstractUser
# AbstractBaseUser 상속
# username, first_name, last_name, email
# is_staff, is_active,  date_joined


# AbstractBaseUser
# password, last_login, is_active


# User 객체
# 속성 - username, password, email(필수요소가 아님), first_name, last_name


# 프로젝트에서 필요한 User
# email 필드 == id 개념 == username
# gender 필드(필수는 아님)
# password
# name 필수


class UserManger(BaseUserManager):
    def _create_user(self, email, password, name, phone, **extra_fields):
        """
        Create and save a user with the given email,password,name.
        """
        if not email:
            raise ValueError("The given email must be set")

        email = self.normalize_email(email)

        user = self.model(email=email, name=name, phone=phone, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, name, phone, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, name, phone, **extra_fields)

    def create_superuser(self, email, password, name, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, name, phone=None, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User 생성 : AbstractUser 상속 or AbstractBaseUser 상속
    필드 추가 : email, password, name, phone

    권한 여부 추가
    """

    # null=True 지정하지 않으면 not null, + unique ==> pk 속성
    email = models.EmailField(verbose_name="이메일", max_length=255, unique=True)
    password = models.CharField(verbose_name="비밀번호", max_length=128)
    name = models.CharField(verbose_name="이름", max_length=64)
    # phone : 비어 있거나 null 허용(선택적 입력)
    phone = models.CharField(verbose_name="핸드폰", max_length=50, blank=True, null=True)

    is_staff = models.BooleanField(verbose_name="관리자여부", default=False)
    is_active = models.BooleanField(verbose_name="활성화여부", default=True)

    # CustomUser 를 기반으로 user 생성을 도와줄 매니저 클래스 등록
    objects = UserManger()  # User.objects.create_user() 생성

    # username(아이디)으로 사용할 필드 지정
    USERNAME_FIELD = "email"

    # email, password 요소 외에 사용자 생성 시 꼭 받아야 하는 필드 작성
    REQUIRED_FIELDS = ["name"]

    def __str__(self) -> str:
        return "<%d %s %s>" % (self.pk, self.email, self.name)

class Profile(models.Model):
    """
    회원가입 시 무조건 같이 실행
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="회원")
    image = models.ImageField(upload_to="profile", default="profile/default.png", verbose_name="프로필 이미지")
    
    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
           Profile.objects.create(user=instance)


class BaseModel(models.Model):
    """
    추상클래스 (껍데기-틀)
    """
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정날짜')
    
    class Meta:
        abstract = True

class Content(BaseModel):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='작성자')
    text = models.TextField(default='')
    
    class Meta:
        ordering = ['-created_at']


def image_upload_to(instance, filename):
    """
    flower.jpg => filename.split('.')[-1] => flower ,jpg
    uuid.uuid4() => 16진수 랜덤값 생성
    00000000-0000-0000-0000-000000000000.jpg
    """
    
    ext = filename.split('.')[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))

class Image(BaseModel):
    UPLOAD_PATH = 'user-upload'
    
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name='작성글')
    image = models.ImageField(upload_to=image_upload_to)
    order = models.SmallIntegerField()

web/django/0203where_final/board/models.py
from django.db import models
from users.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_comment = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('board:index', args=[self.name])

class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    voter = models.ManyToManyField(User, related_name='voter')
    view_cnt = models.BigIntegerField(default=0) # 조회수
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_post')
    notice = models.BooleanField(default=False)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

web/django/0203where_final/direct/models.py
from django.db import models
from users.models import User
from django.db.models import Max

# Create your models here.
class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
	recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
	body = models.TextField(max_length=1000, blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	is_read = models.BooleanField(default=False)

	def send_message(from_user, to_user, body):
		sender_message = Message(
			user=from_user,
			sender=from_user,
			recipient=to_user,
			body=body,
			is_read=True)
		sender_message.save()

		recipient_message = Message(
			user=to_user,
			sender=from_user,
			body=body,
			recipient=from_user,)
		recipient_message.save()
		return sender_message

	def get_messages(user):
		messages = Message.objects.filter(user=user).values('recipient').annotate(last=Max('date')).order_by('-last')
		users = []
		for message in messages:
			users.append({
				'user': User.objects.get(pk=message['recipient']),
				'last': message['last'],
				'unread': Message.objects.filter(user=user, recipient__pk=message['recipient'], is_read=False).count()
				})
		return users

web/django/0203where_final/drink/models.py
from django.db import models


class DrinkMenu(models.Model):
    name = models.CharField(max_length=50, verbose_name="뭐마시지 메뉴이름")
    image = models.ImageField(upload_to="drinkmenu/", default="drinkmenu/drink_default.png", verbose_name="뭐마시지 이미지")
    click_count = models.PositiveIntegerField(default=0, verbose_name="뭐마시지 클릭수")

web/django/0203where_final/eat/models.py
from django.db import models

class FoodCategory(models.Model):
    category = models.CharField(max_length=50, verbose_name="뭐먹지 카테고리")
    
class FoodMenu(models.Model):
    category = models.ForeignKey(FoodCategory, verbose_name="뭐먹지 카테고리", on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name="뭐먹지 메뉴이름")
    image = models.ImageField(upload_to="eatmenu/", default="eatmenu/pizza.png", verbose_name="뭐먹지 이미지")
    click_count = models.PositiveIntegerField(default=0, verbose_name="뭐먹지 클릭수")

web/django/0203where_final/index/models.py
from django.db import models

# Create your models here.

web/django/0203where_final/pay/models.py
from django.db import models
from users.models import User
# Create your models here.

web/django/0203where_final/play/models.py
from django.db import models


class PlayMenu(models.Model):
    name = models.CharField(max_length=50, verbose_name="뭐하지 메뉴이름")
    image = models.ImageField(upload_to="playmenu/", default="playmenu/play_default.png", verbose_name="뭐하지 이미지")
    click_count = models.PositiveIntegerField(default=0, verbose_name="뭐하지 클릭수")

web/django/0203where_final/review/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
#상속모델
from django.contrib.auth.models import AbstractUser
from users.models import User
from django.conf import settings

class Store(models.Model):
    name = models.CharField(max_length=200, verbose_name='가게이름')
    category = models.CharField(max_length=200)
    photo = models.ImageField(blank=True)
    mean_grade = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(5)] ,default=1)

    def __str__(self):
        return self.name


# store모델의 네임과 카테고리 상속받아서 사용
class Review(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    grade = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

web/django/app/users/models.py
from django.db import models

web/django/app2/where/where/users/models.py
from django.db import models

# Create your models here.

web/django/board/board/board/user/models.py
from django.db import models

# Create your models here.

web/django/0203where_final/templates/users/profile.html
{% extends 'base.html' %}
{% load users_tags %}
{% load static %}
{% block contents %}
  <div class="py-4">
    <div class="container">
      <div class="row">
        <!-- Main Content -->
        <aside class="col col-xl-3 order-xl-1 col-lg-12 order-lg-1 col-12">
          <div class="box mb-3 shadow-sm border rounded bg-white profile-box text-center">
            <div class="py-4 px-3 border-bottom">
              <a href="#imageModal" data-bs-toggle="modal" data-bs-target="#imageModal">
                <img src="{{user.profile.image.url}}" class="img-fluid mt-2 rounded-circle" alt="Responsive image" title="프로필 사진 변경">
              </a>
              <h5 class="font-weight-bold text-dark mb-1 mt-4">{{user.name}}님</h5>
              <p class="mb-0 text-muted">UI / UX Designer</p>
            </div>
            <div class="d-flex">
              <div class="col-6 border-right p-3">
                <h6 class="font-weight-bold text-dark mb-1">{% count_post user.id %}</h6>
                <p class="mb-0 text-black-50 small">내가 쓴글</p>
              </div>
              <div class="col-6 p-3">
                <h6 class="font-weight-bold text-dark mb-1">{% count_review user.id %}</h6>
                <p class="mb-0 text-black-50 small">내가 쓴 리뷰</p>
              </div>
            </div>
            <div class="overflow-hidden border-top">
              <a class="font-weight-bold p-3 d-block" href="{% url 'logout' %}">
                Log Out
              </a>
            </div>
          </div>
          {% include 'users/profile_modal.html' %}

        </aside>
        <main class="col col-xl-6 order-xl-2 col-lg-12 order-lg-2 col-md-12 col-sm-12 col-12">
          <div class="box shadow-sm border rounded bg-white mb-3">
            <div class="box-title border-bottom p-3">
              <h6 class="m-0">내 최신글</h6>
            </div>
            {% recent_post 3 user.id as posts %}
            {% for p in posts %}
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveaspectratio="xMidYMid slice" focusable="false">
                  <title>Placeholder</title>
                  <rect width="100%" height="100%" fill="#849B38"/>
                  <text x="50%" y="50%" fill="#849B38" dy=".3em">32x32</text>
                </svg>
                <p class="pb-3 mb-0 small lh-sm border-bottom">
                  <strong class="d-block text-gray-dark">
                    <a href="{% url 'board:detail' p.id %}">{{ p.subject }}</a>
                  </strong>
                  {{p.content|truncatechars:25}}
                </p>
              </div>
            {% endfor %}
          </div>
          <div class="box shadow-sm border rounded bg-white mb-3">
            <div class="box-title border-bottom p-3">
              <h6 class="m-0">Experience</h6>
            </div>
            {% recent_review 3 user.id as reviews %}
            {% for review in reviews %}
              <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveaspectratio="xMidYMid slice" focusable="false">
                  <title>Placeholder</title>
                  <rect width="100%" height="100%" fill="#849B38"/>
                  <text x="50%" y="50%" fill="#849B38" dy=".3em">32x32</text>
                </svg>

                <p class="pb-3 mb-0 small lh-sm border-bottom">
                  <strong class="d-block text-gray-dark">
                    <a href="{% url 'review:review' review.id %}">{{ review.title }}</a>
                  </strong>
                  <a href="">
                    {% if review.photo %}
                      <img style="width: 100px; height: 100px;" src="{{ review.photo.url }}" alt="">
                    {% endif %}
                  </a>
                  <strong>{{review.content|truncatechars:25}}</strong>
                </p>
              </div>
            {% endfor %}
          </div>

        </main>
        <aside class="col col-xl-3 order-xl-3 col-lg-12 order-lg-3 col-12">
          <div class="box shadow-sm border rounded bg-white mb-3">
            <div class="box-title border-bottom p-3">
              <h6 class="m-0">당신의 프로필에 방문한사람</h6>
            </div>
            <div class="box-body p-3">
              <div class="d-flex align-items-center osahan-post-header mb-3 people-list">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="{% static 'img/p4.png' %}" alt="">
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold mr-2">
                  <div class="text-truncate">Sophia Lee</div>
                  <div class="small text-gray-500">@Harvard
                  </div>
                </div>
                <span class="ml-auto">
                  <button type="button" class="btn btn-light btn-sm">메세지 보내기</button>
                </span>
              </div>
              <div class="d-flex align-items-center osahan-post-header mb-3 people-list">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="{% static 'img/p9.png' %}" alt="">
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold mr-2">
                  <div class="text-truncate">John Doe</div>
                  <div class="small text-gray-500">Traveler
                  </div>
                </div>
                <span class="ml-auto">
                  <button type="button" class="btn btn-light btn-sm">메세지 보내기</button>
                </span>
              </div>
              <div class="d-flex align-items-center osahan-post-header mb-3 people-list">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="{% static 'img/p10.png' %}" alt="">
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold mr-2">
                  <div class="text-truncate">Julia Cox</div>
                  <div class="small text-gray-500">Art Designer
                  </div>
                </div>
                <span class="ml-auto">
                  <button type="button" class="btn btn-light btn-sm">메세지 보내기</button>
                </span>
              </div>
              <div class="d-flex align-items-center osahan-post-header mb-3 people-list">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="{% static 'img/p11.png' %}" alt="">
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold mr-2">
                  <div class="text-truncate">Robert Cook</div>
                  <div class="small text-gray-500">@Photography
                  </div>
                </div>
                <span class="ml-auto">
                  <button type="button" class="btn btn-light btn-sm">메세지 보내기</button>
                </span>
              </div>
              <div class="d-flex align-items-center osahan-post-header people-list">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="{% static 'img/p12.png' %}" alt="">
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold mr-2">
                  <div class="text-truncate">Richard Bell</div>
                  <div class="small text-gray-500">@Envato
                  </div>
                </div>
                <span class="ml-auto">
                  <button type="button" class="btn btn-light btn-sm">메세지 보내기</button>
                </span>
              </div>
            </div>
          </div>

        </aside>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    //현재사진삭제 클릭이 되면 a 태그 기능 중지
    //ajax로 요청 보내기 "{% url 'user_profile_delete' %}"

    $(".delete").on("click", function (e) {
      e.preventDefault();

      $.ajax({
        url: "{% url 'user_profile_delete' %}",

        success: function (response) {
          console.log(response);
          location.reload();
          //http : 127.0.0.1:8000/페이지 새로고침
        },
        error: function (req, status, error) {
          console.log(req.responseJSON.message);
        }
      })
    })

    //프로필 사진 변경 클릭 되면 사용자가 변경할 이미지를 선택
    //사용자가 선택한 이미지를 서버로 전송(ajax)

    $("#file").on("change", function (e) {

      const form = document.querySelector("#image_change");

      formData = new FormData(form);

      $.ajax({
        url: "{% url 'user_profile_update' %}", ///http://127.0.0.1:8000/users/profile/update/
        type: "post",
        data: formData,
        processData: false,
        contentType: false,
        success: function (response) {
          console.log(response);
          location.reload(); //http://127.0.0.1:8000/users/profile/페이지 새로고침
        },
        error: function (req, status, error) {
          console.log(req.responseJSON.message);
        }
      })
    })
  </script>
{% endblock script %}

web/django/0203where_final/templates/users/profile_delete.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
      <span class="d-block d-lg-none">Clarence Taylor</span>
      <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" "{% static 'img/drk10.png' %}" alt="..."/></span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">게시판</a>
        </li>

      </ul>
    </div>
  </nav>
  {% include 'navbar.html' %}
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <form method="POST" novalidate="novalidate">
    {% csrf_token %}
    <p>
      <strong>{{ user.user_id }}</strong>
      회원님의 계정이 삭제됩니다.<br>탈퇴시 개인정보 및 이용정보가 삭제되며 복구할 수 없습니다.
      <br>본인의 비밀번호를 입력한 후 하단의 유의사항 동의에 체크하세요.</p>
    <div>
      <label name="label_password" for="{{ password_form.password.id_for_label }}">{{ password_form.password.label }}</label>
      {{ password_form.password }}
      {% if password_form.password.errors %}
        <script type="text/javascript">
          document
            .getElementsByName('password')[0]
            .setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in password_form.password.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% endif %}
      <small>
        본인인증을 위해 비밀번호를 입력해주세요.
      </small>
    </div>

    <label>
      <input type="checkbox" name="ck" onclick="checkDisable(this.form)">
      <span>유의사항 동의</span>
    </label>

    <button type="submit" name="bt" disabled="true">탈퇴하기</button>
  </form>

  <script type="text/javascript">
    function checkDisable(form) {
      if (form.ck.checked == true) {
        form.bt.disabled = false;
      } else {
        form.bt.disabled = true;
      }
    }
  </script>
{% endblock contents %}